### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method launch on channel launch_review)

### ISSUE THREAD

**Issue by BohdanSamusko** [Purus/launch_review#9]
I always get the following exception on iOS device. Have no idea why this happens :( Could you please have a look? 

Unhandled Exception: MissingPluginException(No implementation found for method launch on channel launch_review)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)
<asynchronous suspension>
#1      LaunchReview.launch (package:launch_review/launch_review.dart:10:20)
<asynchronous suspension>
#2      _RateAppState.redirectToStore (package:note_to_email/screens/rate_app.dart:307:18)
#3      _RateAppState.handleSubmitAction.<anonymous closure> (package:note_to_email/screens/rate_app.dart:280:15)
#4      State.setState (package:flutter/src/widgets/framework.dart:1122:30)
#5      _RateAppState.handleSubmitAction (package:note_to_email/screens/rate_app.dart:274:11)
#6      _RateAppState.initState.<anonymous closure> (package:note_to_email/screens/rate_app.dart:73:9)
#7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:513:14)
#8      _InkResponseState.build.<anonymous closure> (package:flutter/src/materi<…>

**Comment by Purus** [comment]
I don't have an iOS device or an Mac. I am sorry I couldn't get you in
this.

iOS support was added by our contributors. Hopefully someone will look on
this.

Thanks,

Purusothaman Ramanujam

**Comment by KaYBlitZ** [comment]
Do you have cocoapods installed? Seems like the iOS library is missing. See https://flutter.dev/docs/get-started/install/macos#deploy-to-ios-devices

**Comment by BohdanSamusko** [comment]
@KaYBlitZ Yes, I have installed cocoapods before.

So, for now, the situation is as following:

1. **lauch_review** plugin doesn't work on iOS and the error is **Unhandled Exception: MissingPluginException(No implementation found for method launch on channel launch_review)**.

2. I decided to rewrite the plugin and create my own plugin to test it and in case of success compare to the current one and find what causes the issue.  
So I have developed my own plugin for launching review. 

3. When I run **'example'** project of my plugin everything works fine and there are no exceptions. The **'example'** project is a project which was created automatically during plugin creation.

4. But, when I add my plugin to my project as a dependency I have got the same error 'Unhandled Exception' on iOS side as it was when I used **lauch_review** plugin. 

5. Supposing the issue is hidden in my project, I created a new flutter project just to test my own plugin and **lauch_review** plugin. And it is very strange but my plugin starts to work okay, but **lauch_review** plugin still throws **'Unhandled Exception'** exception on iOS. 

I am really confused and still try to understand what is happening and try to find where the pitfalls are.  
The situation is like a real detective story))

**Comment by KaYBlitZ** [comment]
Not sure what is going. Does this comment apply to you? https://github.com/flutter/flutter/issues/24171#issuecomment-439667926 . Also does stopping the application first then doing a full rebuild & run fix it? I did some quick googling and people say that hot reload may cause this issue so a full stop and run may be necessary.

**Comment by shantiweb** [comment]
I am getting same issue.

> Unhandled Exception: MissingPluginException(No implementation found for method launch on channel launch_review)

Issue at Android

**Comment by MagnusJohansson** [comment]
@shantiweb I also get this exception if I do `LaunchReview.launch();` , but if I do specify my appId it works: `LaunchReview.launch(androidAppId: "your.app.id");`

**Comment by kharisazhar** [comment]
i'm getting the same problem, try : 

1. uninstall your apps
2. run `flutter clean`

its works .

**Comment by farooqgv** [comment]
> i'm getting the same problem, try :
> 
> 1. uninstall your apps
> 2. run `flutter clean`
> 
> its works .

DON'T DO THIS!!!! It is more likely to break the build forever than fix the issue :/

**Comment by CannaBook** [comment]
> > i'm getting the same problem, try :
> > 
> > 1. uninstall your apps
> > 2. run `flutter clean`
> > 
> > its works .
> 
> DON'T DO THIS!!!! It is more likely to break the build forever than fix the issue :/

Idk what you mean. This works fine. Just remember to use "flutter pub get" after you use "flutter clean"

**Comment by malzariey** [comment]
> i'm getting the same problem, try :
> 
> 1. uninstall your apps
> 2. run `flutter clean`
> 
> its works .

Thanks works after clean :)
